use strict;
use warnings FATAL => 'all';

use File::Spec qw();
use Test::More;
use Test::Exception;
use TestHelper qw(diff_files);

use Procera::SourceFile qw(
    file_path
    preexisting_file_path
);

my $test_file = __FILE__;
my (undef, $test_dir) = File::Basename::fileparse($test_file);

unshift @INC, $test_dir;
my $old_gms_path = $ENV{GMSPATH};
$ENV{GMSPATH} = $test_dir;

my $expected = File::Spec->rel2abs(
    File::Spec->join($test_dir, 'Subject.gms'));
is(preexisting_file_path('Subject'), $expected,
    "Found a preexisting_file_path for Subject at ($expected)");
is(preexisting_file_path('Missing'), undef,
    "Found no preexisting_file_path for Missing");

$expected = File::Spec->join($test_dir, 'expected.gms');
dies_ok(sub {file_path('Missing')}, 'Dies as expected if given an invalid source-path');
diff_files(file_path('Sample'), $expected, 'Autogenerated gms for tool Sample.');

$ENV{GMSPATH} = $old_gms_path;
shift @INC;

done_testing();
